import BoxContent from "../BoxContent/BoxContent";
import Pawn from "../Pawn/Pawn";
import Player from "../Player/Player";
import { BLACK, LengthType, WHITE } from "../utils/type";

export type BoardState = LengthType<LengthType<BoxContent>>;
const playerWhite = new Player(WHITE);
const playerBlack = new Player(BLACK);
export const emptyLine = (): LengthType<BoxContent> => [
  new BoxContent(),
  new BoxContent(),
  new BoxContent(),
  new BoxContent(),
  new BoxContent(),
  new BoxContent(),
  new BoxContent(),
  new BoxContent(),
  new BoxContent(),
  new BoxContent(),
];
export const playerLine = (
  player: Player,
  isEven: boolean
): LengthType<BoxContent> => [
  isEven ? new Pawn(player) : new BoxContent(),
  isEven ? new BoxContent() : new Pawn(player),
  isEven ? new Pawn(player) : new BoxContent(),
  isEven ? new BoxContent() : new Pawn(player),
  isEven ? new Pawn(player) : new BoxContent(),
  isEven ? new BoxContent() : new Pawn(player),
  isEven ? new Pawn(player) : new BoxContent(),
  isEven ? new BoxContent() : new Pawn(player),
  isEven ? new Pawn(player) : new BoxContent(),
  isEven ? new BoxContent() : new Pawn(player),
];
export const onePawnLine = (player: Player): LengthType<BoxContent> => [
  new Pawn(player),
  new BoxContent(),
  new BoxContent(),
  new BoxContent(),
  new BoxContent(),
  new BoxContent(),
  new BoxContent(),
  new BoxContent(),
  new BoxContent(),
  new BoxContent(),
];

export const EMPTY_BOARD: BoardState = [
  emptyLine(),
  emptyLine(),
  emptyLine(),
  emptyLine(),
  emptyLine(),
  emptyLine(),
  emptyLine(),
  emptyLine(),
  emptyLine(),
  emptyLine(),
];

export const ONE_WHITE_PAWN_BOARD: BoardState = [
  onePawnLine(playerWhite),
  emptyLine(),
  emptyLine(),
  emptyLine(),
  emptyLine(),
  emptyLine(),
  emptyLine(),
  emptyLine(),
  emptyLine(),
  emptyLine(),
];
export const CLASSIC_BOARD: BoardState = [
  playerLine(playerWhite, true),
  playerLine(playerWhite, false),
  playerLine(playerWhite, true),
  playerLine(playerWhite, false),
  emptyLine(),
  emptyLine(),
  playerLine(playerBlack, true),
  playerLine(playerBlack, false),
  playerLine(playerBlack, true),
  playerLine(playerBlack, false),
];
export const classicBoard = (player1: Player, player2: Player): BoardState => {
  return [
    playerLine(player1, true),
    playerLine(player1, false),
    playerLine(player1, true),
    playerLine(player1, false),
    emptyLine(),
    emptyLine(),
    playerLine(player2, true),
    playerLine(player2, false),
    playerLine(player2, true),
    playerLine(player2, false),
  ];
};
export const EAT_BOARD: BoardState = [
  playerLine(playerWhite, true),
  playerLine(playerBlack, false),
  emptyLine(),
  playerLine(playerWhite, false),
  playerLine(playerBlack, true),
  playerLine(playerWhite, false),
  emptyLine(),
  emptyLine(),
  emptyLine(),
  emptyLine(),
];

export const TWO_PLAY_BOARD: BoardState = [
  playerLine(playerWhite, true),
  playerLine(playerBlack, false),
  emptyLine(),
  playerLine(playerBlack, false),
  emptyLine(),
  emptyLine(),
  emptyLine(),
  emptyLine(),
  emptyLine(),
  emptyLine(),
];

export const a1PawnBoard = (player: Player): BoardState => [
  onePawnLine(player),
  emptyLine(),
  emptyLine(),
  emptyLine(),
  emptyLine(),
  emptyLine(),
  emptyLine(),
  emptyLine(),
  emptyLine(),
  emptyLine(),
];
export const START_BOARD_JSON = {
  A1: { type: "Pawn", player: "white" },
  C1: { type: "Pawn", player: "white" },
  E1: { type: "Pawn", player: "white" },
  G1: { type: "Pawn", player: "white" },
  I1: { type: "Pawn", player: "white" },
  B2: { type: "Pawn", player: "white" },
  D2: { type: "Pawn", player: "white" },
  F2: { type: "Pawn", player: "white" },
  H2: { type: "Pawn", player: "white" },
  J2: { type: "Pawn", player: "white" },
  A3: { type: "Pawn", player: "white" },
  C3: { type: "Pawn", player: "white" },
  E3: { type: "Pawn", player: "white" },
  G3: { type: "Pawn", player: "white" },
  I3: { type: "Pawn", player: "white" },
  B4: { type: "Pawn", player: "white" },
  D4: { type: "Pawn", player: "white" },
  F4: { type: "Pawn", player: "white" },
  H4: { type: "Pawn", player: "white" },
  J4: { type: "Pawn", player: "white" },
  A7: { type: "Pawn", player: "black" },
  C7: { type: "Pawn", player: "black" },
  E7: { type: "Pawn", player: "black" },
  G7: { type: "Pawn", player: "black" },
  I7: { type: "Pawn", player: "black" },
  B8: { type: "Pawn", player: "black" },
  D8: { type: "Pawn", player: "black" },
  F8: { type: "Pawn", player: "black" },
  H8: { type: "Pawn", player: "black" },
  J8: { type: "Pawn", player: "black" },
  A9: { type: "Pawn", player: "black" },
  C9: { type: "Pawn", player: "black" },
  E9: { type: "Pawn", player: "black" },
  G9: { type: "Pawn", player: "black" },
  I9: { type: "Pawn", player: "black" },
  B10: { type: "Pawn", player: "black" },
  D10: { type: "Pawn", player: "black" },
  F10: { type: "Pawn", player: "black" },
  H10: { type: "Pawn", player: "black" },
  J10: { type: "Pawn", player: "black" },
};
export const START_BOARD_ARRAY = [
  [
    { player: "white", type: "Pawn" },
    undefined,
    { player: "white", type: "Pawn" },
    undefined,
    { player: "white", type: "Pawn" },
    undefined,
    { player: "white", type: "Pawn" },
    undefined,
    { player: "white", type: "Pawn" },
    undefined,
  ],
  [
    undefined,
    { player: "white", type: "Pawn" },
    undefined,
    { player: "white", type: "Pawn" },
    undefined,
    { player: "white", type: "Pawn" },
    undefined,
    { player: "white", type: "Pawn" },
    undefined,
    { player: "white", type: "Pawn" },
  ],
  [
    { player: "white", type: "Pawn" },
    undefined,
    { player: "white", type: "Pawn" },
    undefined,
    { player: "white", type: "Pawn" },
    undefined,
    { player: "white", type: "Pawn" },
    undefined,
    { player: "white", type: "Pawn" },
    undefined,
  ],
  [
    undefined,
    { player: "white", type: "Pawn" },
    undefined,
    { player: "white", type: "Pawn" },
    undefined,
    { player: "white", type: "Pawn" },
    undefined,
    { player: "white", type: "Pawn" },
    undefined,
    { player: "white", type: "Pawn" },
  ],
  [
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
  ],
  [
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
  ],
  [
    { player: "black", type: "Pawn" },
    undefined,
    { player: "black", type: "Pawn" },
    undefined,
    { player: "black", type: "Pawn" },
    undefined,
    { player: "black", type: "Pawn" },
    undefined,
    { player: "black", type: "Pawn" },
    undefined,
  ],
  [
    undefined,
    { player: "black", type: "Pawn" },
    undefined,
    { player: "black", type: "Pawn" },
    undefined,
    { player: "black", type: "Pawn" },
    undefined,
    { player: "black", type: "Pawn" },
    undefined,
    { player: "black", type: "Pawn" },
  ],
  [
    { player: "black", type: "Pawn" },
    undefined,
    { player: "black", type: "Pawn" },
    undefined,
    { player: "black", type: "Pawn" },
    undefined,
    { player: "black", type: "Pawn" },
    undefined,
    { player: "black", type: "Pawn" },
    undefined,
  ],
  [
    undefined,
    { player: "black", type: "Pawn" },
    undefined,
    { player: "black", type: "Pawn" },
    undefined,
    { player: "black", type: "Pawn" },
    undefined,
    { player: "black", type: "Pawn" },
    undefined,
    { player: "black", type: "Pawn" },
  ],
];

export const ONE_PLAY_BOARD_ARRAY = [
  [
    { player: "white", type: "Pawn" },
    undefined,
    { player: "white", type: "Pawn" },
    undefined,
    { player: "white", type: "Pawn" },
    undefined,
    { player: "white", type: "Pawn" },
    undefined,
    { player: "white", type: "Pawn" },
    undefined,
  ],
  [
    undefined,
    { player: "white", type: "Pawn" },
    undefined,
    { player: "white", type: "Pawn" },
    undefined,
    { player: "white", type: "Pawn" },
    undefined,
    { player: "white", type: "Pawn" },
    undefined,
    { player: "white", type: "Pawn" },
  ],
  [
    { player: "white", type: "Pawn" },
    undefined,
    { player: "white", type: "Pawn" },
    undefined,
    { player: "white", type: "Pawn" },
    undefined,
    { player: "white", type: "Pawn" },
    undefined,
    { player: "white", type: "Pawn" },
    undefined,
  ],
  [
    undefined,
    undefined,
    undefined,
    { player: "white", type: "Pawn" },
    undefined,
    { player: "white", type: "Pawn" },
    undefined,
    { player: "white", type: "Pawn" },
    undefined,
    { player: "white", type: "Pawn" },
  ],
  [
    { player: "white", type: "Pawn" },
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
  ],
  [
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
  ],
  [
    { player: "black", type: "Pawn" },
    undefined,
    { player: "black", type: "Pawn" },
    undefined,
    { player: "black", type: "Pawn" },
    undefined,
    { player: "black", type: "Pawn" },
    undefined,
    { player: "black", type: "Pawn" },
    undefined,
  ],
  [
    undefined,
    { player: "black", type: "Pawn" },
    undefined,
    { player: "black", type: "Pawn" },
    undefined,
    { player: "black", type: "Pawn" },
    undefined,
    { player: "black", type: "Pawn" },
    undefined,
    { player: "black", type: "Pawn" },
  ],
  [
    { player: "black", type: "Pawn" },
    undefined,
    { player: "black", type: "Pawn" },
    undefined,
    { player: "black", type: "Pawn" },
    undefined,
    { player: "black", type: "Pawn" },
    undefined,
    { player: "black", type: "Pawn" },
    undefined,
  ],
  [
    undefined,
    { player: "black", type: "Pawn" },
    undefined,
    { player: "black", type: "Pawn" },
    undefined,
    { player: "black", type: "Pawn" },
    undefined,
    { player: "black", type: "Pawn" },
    undefined,
    { player: "black", type: "Pawn" },
  ],
];
