import Box from "./Box";
import Pawn from "./Pawn";
import Player from "./Player";
import { BLACK, BOTTOM, LengthType, TOP, WHITE } from "./utils/type";

export type BoardState = LengthType<LengthType<Box>>;

export const EMPTY_BOARD: BoardState = [
  [
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
  ],
  [
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
  ],
  [
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
  ],
  [
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
  ],
  [
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
  ],
  [
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
  ],
  [
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
  ],
  [
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
  ],
  [
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
  ],
  [
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
  ],
];
const playerWhite = new Player(WHITE, TOP, "Moutarde");
const playerBlack = new Player(BLACK, BOTTOM, "Moutarde");
export const CLASSIC_BOARD: BoardState = [
  [
    new Pawn(playerWhite),
    new Box(),
    new Pawn(playerWhite),
    new Box(),
    new Pawn(playerWhite),
    new Box(),
    new Pawn(playerWhite),
    new Box(),
    new Pawn(playerWhite),
    new Box(),
  ],
  [
    new Box(),
    new Pawn(playerWhite),
    new Box(),
    new Pawn(playerWhite),
    new Box(),
    new Pawn(playerWhite),
    new Box(),
    new Pawn(playerWhite),
    new Box(),
    new Pawn(playerWhite),
  ],
  [
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
  ],
  [
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
  ],
  [
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
  ],
  [
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
  ],
  [
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
  ],
  [
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
    new Box(),
  ],
  [
    new Pawn(playerBlack),
    new Box(),
    new Pawn(playerBlack),
    new Box(),
    new Pawn(playerBlack),
    new Box(),
    new Pawn(playerBlack),
    new Box(),
    new Pawn(playerBlack),
    new Box(),
  ],
  [
    new Box(),
    new Pawn(playerBlack),
    new Box(),
    new Pawn(playerBlack),
    new Box(),
    new Pawn(playerBlack),
    new Box(),
    new Pawn(playerBlack),
    new Box(),
    new Pawn(playerBlack),
  ],
];
